### ISSUE TITLE
Panic on rendering certain files with raqote

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#145]
The attached file causes a panic when rendering with the raqote backend. It renders fine with cairo backend. The file is zipped so that github would accept the upload. 

Backtrace:
```
> env RUST_BACKTRACE=1 /home/shnatsel/Code/resvg/target/release/rendersvg --backend=raqote status/48/night-light-symbolic.svg ~/out.png
thread 'main' panicked at 'index 2313 out of range for slice of length 2304', src/libcore/slice/mod.rs:2560:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2560
   9: <raqote::blitter::ImagePadAlphaShader as raqote::blitter::Shader>::shade_span
  10: <raqote::blitter::ShaderBlendBlitter as raqote::blitter::Blitter>::blit_span
  11: raqote::draw_target::DrawTarget::composite
  12: raqote::draw_target::DrawTarget::fill
  13: raqote::draw_target::DrawTarget::draw_image_at
  14: resvg::backend_raqote::filter::copy_image
  15: <resvg::backend_raqote::filter::RaqoteFilter as resvg::backend_utils::filter::Filter<raqote::draw_target::DrawTarget>>::get_input
  16: resvg::backend_raqote::filter::apply
  17: resvg::backend_raqote::render_node
  18: resvg::backend_raqote::render_group
  19: resvg::backend_raqote::render_node
  20: resvg::backend_raqote::render_node_to_canvas
  21: resvg::backend_raqote::render_to_canvas
  22: resvg::backend_raqote::render_to_image
  23: <resvg::backend_raqote::Backend as resvg::Render>::render_to_image
  24: rendersvg::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  28: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  29: main
  30: __libc_start_main
  31: _start
```
[night-light-symbolic.svg.zip](https://github.com/RazrFalcon/resvg/files/3311845/night-light-symbolic.svg.zip)

**Comment by Shnatsel** [comment]
I'm using raqote 0.5.3 and resvg from it at commit ec197b40db61256dedd9372d986a9c21c3cf2694
Here's the Cargo.lock: [Cargo.lock.zip](https://github.com/RazrFalcon/resvg/files/3311851/Cargo.lock.zip)

**Comment by Shnatsel** [comment]
cc @jrmuizel since the backtrace points to raqote itself
