### ISSUE TITLE
Panic on rendering some elementary icons with Raqote backend

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#288]
Triggered e.g. by the `actions/24/object-flip-vertical.svg` file, attached: [object-flip-vertical.svg.gz](https://github.com/RazrFalcon/resvg/files/4704564/object-flip-vertical.svg.gz)

Found with rendersvg tool on commit 7e32794d78dfe58887a9f30d4a90fa8fbfee03aa. Reproducible with both bundled Cargo.lock and after running `cargo update`. Cairo backend is not affected.

Backtrace:
```
thread 'main' panicked at 'attempt to divide by zero', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/sw-composite-0.7.6/src/lib.rs:272:27
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: sw_composite::Gradient::build_lut
  15: sw_composite::Gradient::make_source
  16: raqote::blitter::choose_shader
  17: raqote::draw_target::DrawTarget::composite
  18: raqote::draw_target::DrawTarget::fill
  19: raqote::draw_target::DrawTarget::stroke
  20: resvg::backend_raqote::style::stroke
  21: resvg::backend_raqote::path::draw
  22: resvg::backend_raqote::render_node
  23: resvg::backend_raqote::render_group
  24: resvg::backend_raqote::render_node
  25: resvg::backend_raqote::render_group
  26: resvg::backend_raqote::render_node
  27: resvg::backend_raqote::render_node_to_canvas_impl
  28: resvg::backend_raqote::render_to_canvas
  29: resvg::backend_raqote::render_to_image
  30: <resvg::backend_raqote::Backend as resvg::Render>::render_to_image
  31: rendersvg::main
  32: std::rt::lang_start::{{closure}}
  33: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  34: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  35: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  36: std::panicking::try
             at src/libstd/panicking.rs:281
  37: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  38: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  39: main
  40: __libc_start_main
  41: _start
```

**Comment by RazrFalcon** [comment]
Looks like a Raqote bug.

**Comment by Shnatsel** [comment]
I'll report a bug for Raqote then. The panic originates in `sw-composite`, I wasn't sure against which repo I should report it so I've reported here.

**Comment by RazrFalcon** [comment]
Yes, `sw_composite` is part of raqote.

**Comment by Shnatsel** [comment]
This is fixed upstream, closing.
